Repository TheDeveloper88/cpp-programs-dictionary, pull requests merged in 2020-10, with the labels that each got.

#5 Update README.md
  README.md
Labels: documentation, good first issue

#3 Create quicksort.cpp
  quicksort.cpp
Labels: good first issue

#6 Update BubbleSort.cpp
  BubbleSort.cpp
Labels: hacktoberfestaccepted, hactoberfest

#7 Create maximizingXOR.cpp
  maximizingXOR.cpp
Labels: hacktoberfestaccepted, hactoberfest

#8 SumOfDigits.cpp is added.
  SumOfDigits.cpp
Labels: hacktoberfestaccepted, hactoberfest

#9 Greedy Algorithms in C++
  Dijkstra.cpp
  Knapsack.cpp
  Kruskals Minimum Spanning Tree.cpp
  Prims Minimum Spanning Tree.cpp
Labels: hacktoberfestaccepted, hactoberfest
